# Generated by Django 4.0.2 on 2022-07-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pu口袋校园',
                'managed': False,
            },
        ),
    ]
